### ISSUE TITLE
Provide `url` in `_config.yml`.

### ISSUE THREAD

**Issue by siko1056** [me-ydv-5/me-ydv-5.github.io#3]
https://github.com/me-ydv-5/me-ydv-5.github.io/blob/dea5b81281d91a6f3df5279ec0fdf081a7398739/_config.yml#L18

Please provide the `url`, e.g. `https://batterylow.me` otherwise planet.octave.org seems confused parsing your feeds... (kind of works, but maybe this helps :wink: )

**Comment by me-ydv-5** [comment]
I intentionally removed the url from here because I also observed this problem on planet octave. Even after now adding this, still the domain on planet octave appears to be `batterylow.me/batterylow.me/`. Kindly check if there's a problem in the url string added on aggregator. If there isn't any problem, then I'll remove `batterylow.me` from CNAME records of `me-ydv-5.github.io` and we can just use the latter instead.

**Comment by siko1056** [comment]
Currently planet.octave.org tries to get the feeds from the url `https://batterylow.me/feed.xml`.  This seems to be working only partially, because the importing process always returns with something like

    ERROR:planet:Error 500 while updating feed <http://batterylow.me/feed.xml>

And as you can see in the right subscriptions column in https://planet.octave.org/, something goes wrong. The urls inside your posts are good.  Is the file https://github.com/me-ydv-5/me-ydv-5.github.io/blob/00b3c8c7330d0b70936d120aa9e4de5846678f9a/CNAME#L1 somehow involved in getting HTTP and HTTPS wrong?

**Comment by me-ydv-5** [comment]
I figured it out, the reason for this was, I had forwarded all the HTTP requests to HTTPS in the cloudflare server which manages the SSL for `batterylow.me`.  So everytime someone tries to access `http://batterylow.me`, they are forced on to an HTTPS connection. 

I have removed the CNAME record `batterylow.me`, once and for all now, I'd request you to link the new feed for `https://me-ydv-5.github.io/feed.xml` and kindly let me know if everything seems okay. battery has really become low this time for `batterylow.me`.

**Comment by siko1056** [comment]
Kind of works.  Maybe you take a look at my `_config.yml`? I think now you over specified many urls in your "minor commit" fb0d57e99ee9ad3ca806acb2bf4409fde96de737 ...

Just provide a proper `url` in `_config.yml`, e.g. `https://me-ydv-5.github.io`. Because now both is valid?! :confused: 

- https://me-ydv-5.github.io/
- https://me-ydv-5.github.io/me-ydv-5.github.io/

**Comment by me-ydv-5** [comment]
Please see if the issue has been resolved.

**Comment by siko1056** [comment]
Thanks for caring. Both urls of my previous comment are still working, but nevermind. On planet everything looks good. Back to the "real" problems :wink:
